copaunca/urls.py
from django.contrib import admin
from django.urls import path
from cpunca import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admncpunca24/', admin.site.urls),
    path('', views.raiz),
    path('tabla_posiciones_copa_unca/', views.tabla_posiciones_unca, name='tabla_posiciones'),
    path('resultados_copa_unca/', views.mostrar_partidos_unca, name='partidos'),
    path('resultados_copa_unca/<int:pk>/', views.resumen_unca, name='resumen'),
    path('copa_unca/', views.deportes_unca),
    path('campeones_copa_unca/', views.tabla_campeones_unca),
    path('100m/', views.cienmetros),
    path('200m/', views.doscientosmetros),
    path('4x100/', views.cuatrocientosmetros),
    path('disco/', views.disco),
    path('bala/', views.bala),
    path('jabalina/', views.jabalina),
    path('saltolargo/', views.saltolargo),
    path('saltotriple/', views.saltotriple),
    path('ciclismo/', views.ciclismo),
    path('tabla_atletismo/', views.tabla_atletismo),
    path ('noticias', views.blog),
    path ('noticias/<slug:pk>', views.single_blog, name='single_blog'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cpunca/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

class EquipoUnca(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class PartidoUnca(models.Model):
    DEPORTE_CHOICES = (
        ('FUTBOL_FEMENINO', 'Fútbol de Campo Femenino'),
        ('FUTBOL_MASCULINO', 'Fútbol de Campo Masculino'),
        ('FUTSAL_FEMENINO', 'Fútsal Femenino'),
        ('FUTSAL_MASCULINO', 'Fútsal Masculino'),
        ('HANDBALL_FEMENINO', 'Handball Femenino'),
        ('HANDBALL_MASCULINO', 'Handball Masculino'),
        ('VOLLEY_FEMENINO', 'Volley Femenino'),
        ('VOLLEY_MASCULINO', 'Volley Masculino'),
        ('BASKET_FEMENINO', 'Básquet Femenino'),
        ('BASKET_MASCULINO', 'Básquet Masculino'),
        ('FUTBOL_UNIVERSITARIO', 'Fútbol Universitario'),
        ('PIKI', 'Piki'),
        ('AJEDREZ', 'Ajedrez'),
        ('PING_PONG', 'Ping Pong'),
    )


    equipo_local = models.ForeignKey(EquipoUnca, on_delete=models.CASCADE, related_name='partidos_local')
    equipo_visitante = models.ForeignKey(EquipoUnca, on_delete=models.CASCADE, related_name='partidos_visitante')
    goles_local = models.PositiveIntegerField(blank=True, null=True)
    goles_visitante = models.PositiveIntegerField(blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    partido_numero = models.CharField(max_length=100, blank=True, null=True)
    fase_partido = models.CharField(max_length=99, blank=True, null=True)
    deporte = models.CharField(max_length=50, choices=DEPORTE_CHOICES, blank=True, null=True)


    def __str__(self):
        return f"PartidoUnca {self.id} {self.equipo_local} vs {self.equipo_visitante}"

    def get_absolute_url(self):
        return reverse('resumen_unca', kwargs={'pk': self.pk})


class EventoPartidoUnca(models.Model):
    PARTIDO_EVENT_CHOICES = (
        ('INICIO DEL PARTIDO', 'Inicio del partido'),
        ('PENDIENTE', 'Pendiente'),
        ('FINAL DEL PARTIDO', 'Fin del partido'),
    )

    partido = models.ForeignKey(PartidoUnca, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=100, choices=PARTIDO_EVENT_CHOICES)
    minuto = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.tipo} en el minuto {self.minuto} del partido {self.partido}"


class EventosUnca(models.Model):
    PARTIDO_EVENT_CHOICES = (
        ('GOOOOL', 'Gol local'),
        ('GOOOL', 'Gol visitante'),
        ('PUNTO', 'Punto local'),
        ('PUNTO ', 'Punto visitante'),
        ('TARJETA ROJA', 'Tarjeta roja local'),
        ('TARJETA ROJA ', 'Tarjeta roja visitante'),
        ('TARJETA AMARILLA', 'Tarjeta amarilla local'),
        ('TARJETA AMARILLA ', 'Tarjeta amarilla visitante'),
    )

    partido = models.ForeignKey(PartidoUnca, on_delete=models.CASCADE)
    minuto = models.PositiveIntegerField()
    tipo = models.CharField(max_length=100, choices=PARTIDO_EVENT_CHOICES)
    jugadores = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.tipo} en el minuto {self.minuto} del partido {self.partido}"

from django.db import models

class PosicionUnca(models.Model):
    equipo = models.ForeignKey(EquipoUnca, on_delete=models.CASCADE)
    puntos_futbol_fem = models.IntegerField(default=0)
    puntos_futbol_masc = models.IntegerField(default=0)
    puntos_futsal_fem = models.IntegerField(default=0)
    puntos_futsal_masc = models.IntegerField(default=0)
    puntos_handball_fem = models.IntegerField(default=0)
    puntos_handball_masc = models.IntegerField(default=0)
    puntos_volley_fem = models.IntegerField(default=0)
    puntos_volley_masc = models.IntegerField(default=0)
    puntos_basket_fem = models.IntegerField(default=0)
    puntos_basket_masc = models.IntegerField(default=0)
    puntos_futbol_universitario = models.IntegerField(default=0)
    puntos_piki = models.IntegerField(default=0)
    puntos_ajedrez = models.IntegerField(default=0)
    puntos_pingpong = models.IntegerField(default=0)
    puntos_ciclismofem = models.IntegerField(default=0)
    puntos_ciclismomasc = models.IntegerField(default=0)
    puntos_atletismo = models.IntegerField(default=0)
    puntos = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.equipo}"


class CampeonUnca(models.Model):
    equipo = models.ForeignKey(EquipoUnca, on_delete=models.CASCADE)
    campeon_2016 = models.IntegerField(default=0,)
    campeon_2017 = models.IntegerField(default=0)
    campeon_2018 = models.IntegerField(default=0)
    campeon_2019 = models.IntegerField(default=0)
    campeon_2022 = models.IntegerField(default=0)
    campeon_2023 = models.IntegerField(default=0)
    total_campeonatos = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.equipo}"

class TablaPosicionesUnca(models.Model):
    equipo = models.ForeignKey(EquipoUnca, on_delete=models.CASCADE)
    puntos = models.PositiveIntegerField(default=0)
    partidos_jugados = models.PositiveIntegerField(default=0)
    partidos_ganados = models.PositiveIntegerField(default=0)
    partidos_empatados = models.PositiveIntegerField(default=0)
    partidos_perdidos = models.PositiveIntegerField(default=0)
    goles_favor = models.PositiveIntegerField(default=0)
    goles_contra = models.PositiveIntegerField(default=0)
    diferencia_goles = models.IntegerField(default=0)
    @staticmethod
    def calcular_posiciones():
        equipos = EquipoUnca.objects.all()
        TablaPosicionesUnca.objects.all().delete()
        for equipo in equipos:
            partidos_local = PartidoUnca.objects.filter(equipo_local=equipo)
            partidos_visitante = PartidoUnca.objects.filter(equipo_visitante=equipo)
            partidos_jugados = partidos_local.count() + partidos_visitante.count()
            partidos_ganados = partidos_local.filter(goles_local__gt=models.F('goles_visitante')).count()
            partidos_ganados += partidos_visitante.filter(goles_visitante__gt=models.F('goles_local')).count()
            partidos_empatados = partidos_local.filter(goles_local=models.F('goles_visitante')).count()
            partidos_empatados += partidos_visitante.filter(goles_visitante=models.F('goles_local')).count()
            partidos_perdidos = partidos_jugados - partidos_ganados - partidos_empatados
            goles_favor = partidos_local.aggregate(total=models.Sum('goles_local'))['total'] or 0
            goles_favor += partidos_visitante.aggregate(total=models.Sum('goles_visitante'))['total'] or 0
            goles_contra = partidos_local.aggregate(total=models.Sum('goles_visitante'))['total'] or 0
            goles_contra += partidos_visitante.aggregate(total=models.Sum('goles_local'))['total'] or 0
            puntos = partidos_ganados * 3 + partidos_empatados
            diferencia_goles = goles_favor - goles_contra
            TablaPosicionesUnca.objects.create(
                equipo=equipo,
                puntos=puntos,
                partidos_jugados=partidos_jugados,
                partidos_ganados=partidos_ganados,
                partidos_empatados=partidos_empatados,
                partidos_perdidos=partidos_perdidos,
                goles_favor=goles_favor,
                goles_contra=goles_contra,
                diferencia_goles=diferencia_goles
            )
@receiver(post_save, sender=PartidoUnca)
def actualizar_tabla_posiciones(sender, instance, **kwargs):
    TablaPosicionesUnca.calcular_posiciones()


class DeporteUnca(models.Model):
    foto = models.ImageField(null=True, blank=True)
    nombre = models.CharField(max_length=300)
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.nombre

class ChampionUnca(models.Model):
    foto = models.ImageField(null=True, blank=True)
    nombre = models.CharField(max_length=300)
    link = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.nombre

class ChampiongralUnca(models.Model):
    foto = models.ImageField(null=True, blank=True)
    nombre = models.CharField(max_length=300)
    link = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.nombre


class Categoria1 (models.Model):
    nombre = models.CharField(null= False, blank= True, max_length=100)

    def __str__(self):
        return self.nombre


class Categoria2 (models.Model):
    nombre = models.CharField(null= False, blank= True, max_length=100)

    def __str__(self):
        return self.nombre

class Categoria3 (models.Model):
    nombre = models.CharField(null= False, blank= True, max_length=100)

    def __str__(self):
        return self.nombre


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    foto = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    categoria1 = models.ForeignKey('Categoria1', on_delete=models.CASCADE,null=True)
    categoria2 = models.ForeignKey ('Categoria2', on_delete=models.CASCADE, null=True)
    categoria3 = models.ForeignKey('Categoria3', on_delete=models.CASCADE, null=True)
    published_date = models.DateTimeField(blank=True, null=True)
    slug= models.SlugField(null=False, default="#")

    def get_absolute_url(self):
        return reverse('single_blog', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

templates/copaunca.html
{% include "headercpunca.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cupingcss/stylecup.css' %}">
     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">

    <style>
        /* Estilos para agregar espacio entre partidos */
        .partido-container {
            margin-bottom: 20px;
        }

        /* Estilos para resaltar los partidos */
        .partido {
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .partido:hover {
            background-color: #e5e5e5;
        }

        .hidden {
          display: none;
        }
    </style>
</head>
<body>

   	<!-- Breadcrumb section -->
	<div class="site-breadcrumb">
		<div class="container">

		</div>
	</div>
	<!-- Breadcrumb section end -->
    <div class="container">
    <ol class="breadcrumb" style="background-color: transparent;">
      <!--<li class="breadcrumb-item" ><a href="/" style="color: black"><i class="fa fa-home" style="color: black"></i> Inicio</a> </li>
      <li class="breadcrumb-item active">Deportes</li>-->
    </ol>
    </div>

	<!-- Breadcrumb section end -->
    
    <div class="section-title text-center">
    <h2 id="welcome-text-1" style="color: #009813;"> Bienvenido a la </h2>
</div>

<img id="welcome-image" style="display: block; margin: 0 auto; max-width: 350px; height: auto; opacity: 0;" src="{% static 'image/cpunca24.png' %}"><br><br>

<div class="section-title text-center">
    <h2 id="welcome-text-2" style="color: #009813;"> 8va Edición!</h2>
</div>
    <br><br>
                <button lang="es" type="button" class="btn btn-secondary btn-lg" style="display: block; background: #009813; border-radius: 20px; margin-right: auto; margin-left: auto"><i class="fa fa-file-pdf-o"></i>
                    <a lang="es" href="#" style="color: white; "> Reglamento Copa Unca 2024</a>
                </button><br><br><br>


    
	<!-- Team section  -->
<section class="full-courses-section spad pt-0">
    <div class="container">
        <div class="section-title text-center">
            <!--<h3 style="text-decoration: none">Modalidades</h3>-->
            <h4 data-aos="fade-up">Todas las modalidades de la competencia</h4>
        </div>
        <div class="row">
            {% for deporteunca in deportes %}
            <div class="col-md-6 col-lg-3">
                <a href="{{ deporteunca.link }}">
                    <div class="member">
                        <div class="member-pic set-bg" data-setbg="{% static 'image/' %}{{ deporteunca.foto }}">
                            
                        </div>
                        <!--<h5 style="padding-bottom: 20px;">{{ deporteunca.nombre }}</h5>-->
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

    
	<!-- Team section end -->
    <!-- Blog section -->
	<section class="blog-section spad">
		<div class="container">
			<div class="section-title text-center">
                <h4><i class="fa fa-newspaper-o"></i> FEUNCA Noticias</h4>
				
			</div>
			<div class="row">
                {% for post in posts %}
				<div class="col-xl-6 col-md-6 col-sm-12">
					<div class="blog-item" id="blogItem">
						<div class="blog-thumb set-bg" data-setbg="{% static "image/" %}{{ post.foto }}"></div>
						<div class="blog-content">
                            <h4><a href="/noticias/{{ post.id }}" style="color:black">{{ post.title }}</a></h4>
							<div class="blog-meta">
								<span><i class="fa fa-calendar-o"></i> {{ post.published_date }} </span>
								<span><i class="fa fa-user"></i> {{ post.author }} </span>
							</div>
							<p>{{ post.text|truncatewords:"25" }}</p>
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>
	<!-- Blog section -->

    {% include "pie_pagina.html" %}
    <script src="{% static 'js/cupingjs/script.js' %}"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const textElement1 = document.getElementById('welcome-text-1');
            const textElement2 = document.getElementById('welcome-text-2');
            const text1 = textElement1.innerHTML;
            const text2 = textElement2.innerHTML;
            const imageElement = document.getElementById('welcome-image');
            
            textElement1.innerHTML = ''; // Limpiar el texto original
            textElement2.innerHTML = ''; // Limpiar el texto original
        
            let index1 = 0;
            let index2 = 0;
        
            function typeWriter1() {
                if (index1 < text1.length) {
                    textElement1.innerHTML += text1.charAt(index1);
                    index1++;
                    setTimeout(typeWriter1, 100); // Ajustar la velocidad aquí
                } else {
                    textElement1.style.borderRight = 'none'; // Eliminar el cursor después de que termine el tipeo
                    fadeInImage();
                }
            }
        
            function fadeInImage() {
                imageElement.style.opacity = 1; // Mostrar la imagen con desvanecimiento
                setTimeout(typeWriter2, 500); // Iniciar la animación del segundo texto después de la imagen
            }
        
            function typeWriter2() {
                if (index2 < text2.length) {
                    textElement2.innerHTML += text2.charAt(index2);
                    index2++;
                    setTimeout(typeWriter2, 100); // Ajustar la velocidad aquí
                } else {
                    textElement2.style.borderRight = 'none'; // Eliminar el cursor después de que termine el tipeo
                }
            }
        
            typeWriter1(); // Iniciar la animación del primer texto
        });


    </script>
</body>
</html>

templates/partidosunca.html
{% include "headercpunca.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cupingcss/stylecup.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">

    <style>
        /* Estilos para agregar espacio entre partidos */
        .partido-container {
            margin-bottom: 20px;
        }

        /* Estilos para resaltar los partidos */
        .partido {
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .partido:hover {
            background-color: #e5e5e5;
        }

        .hidden {
          display: none;
        }
        .select2-container--default .select2-selection--single {
            border-radius: 20px !important;
            width: 100% !important;
            box-sizing: border-box;
            border: 1px solid #ccc;
        }

        .select2-container--default .select2-selection--single .select2-selection__rendered {
            border-radius: 20px !important;
        }
        .select2-container--default .select2-search {
            display: none !important;
        }
        .select2-container--default .select2-results__option--highlighted {
            background-color: #009813 !important;
            color: white !important;
        }
    </style>
</head>
<body>

    <!-- Breadcrumb section -->
    <div class="site-breadcrumb"></div>
    <div class="container">
        <ol class="breadcrumb" style="background-color: transparent;"></ol>
    </div>

    <!-- Código Nuevo -->
    <section class="full-courses-section spad pt-0">
        <h5 class="h3-stylecup">Todas las competencias</h5>
        <img style="display: block; margin: 0 auto; max-width: 250px; height: auto;" src="{% static 'image/cpunca6.png' %}"><br><br>

        <div style="text-align: center;">
            <form id="deporteForm" method="get">
                <select id="deporte" name="deporte" style="border-radius: 20px; padding: 15px;">
                    <option value="FUTBOL_FEMENINO" data-icon="fa-solid fa-futbol" {% if request.GET.deporte == "FUTBOL_FEMENINO" %}selected{% endif %}>Fútbol de Campo Femenino</option>
                    <option value="FUTBOL_MASCULINO" data-icon="fa-solid fa-futbol" {% if request.GET.deporte == "FUTBOL_MASCULINO" %}selected{% endif %}>Fútbol de Campo Masculino</option>
                    <option value="FUTSAL_FEMENINO" data-icon="fa-solid fa-futbol" {% if request.GET.deporte == "FUTSAL_FEMENINO" %}selected{% endif %}>Fútbol de Salón Femenino</option>
                    <option value="FUTSAL_MASCULINO" data-icon="fa-solid fa-futbol" {% if request.GET.deporte == "FUTSAL_MASCULINO" %}selected{% endif %}>Fútbol de Salón Masculino</option>
                    <option value="HANDBALL_FEMENINO" data-icon="fa-solid fa-angle-double-down" {% if request.GET.deporte == "HANDBALL_FEMENINO" %}selected{% endif %}>Handball Femenino</option>
                    <option value="HANDBALL_MASCULINO" data-icon="fa-solid fa-angle-double-down" {% if request.GET.deporte == "HANDBALL_MASCULINO" %}selected{% endif %}>Handball Masculino</option>
                    <option value="VOLLEY_FEMENINO" data-icon="fa-solid fa-volleyball" {% if request.GET.deporte == "VOLLEY_FEMENINO" %}selected{% endif %}>Volley Femenino</option>
                    <option value="VOLLEY_MASCULINO" data-icon="fa-solid fa-volleyball" {% if request.GET.deporte == "VOLLEY_MASCULINO" %}selected{% endif %}>Volley Masculino</option>
                    <option value="BASKET_FEMENINO" data-icon="fa-solid fa-basketball" {% if request.GET.deporte == "BASKET_FEMENINO" %}selected{% endif %}>Basquet Femenino</option>
                    <option value="BASKET_MASCULINO" data-icon="fa-solid fa-basketball" {% if request.GET.deporte == "BASKET_MASCULINO" %}selected{% endif %}>Basquet Masculino</option>
                    <option value="FUTBOL_UNIVERSITARIO" data-icon="fa-solid fa-futbol" {% if request.GET.deporte == "FUTBOL_UNIVERSITARIO" %}selected{% endif %}>Fútbol Universitario</option>
                    <option value="PIKI" data-icon="fa-solid fa-volleyball" {% if request.GET.deporte == "PIKI" %}selected{% endif %}>Piki</option>
                    <option value="AJEDREZ" data-icon="fa-solid fa-chess" {% if request.GET.deporte == "AJEDREZ" %}selected{% endif %}>Ajedrez</option>
                    <option value="PING_PONG" data-icon="fa-solid fa-table-tennis" {% if request.GET.deporte == "PING_PONG" %}selected{% endif %}>Ping Pong</option>
                    <option value="ATLETISMO" data-icon="fa-solid fa-biking" data-url="/ciclismo">Ciclismo</option>
                    <option value="ATLETISMO" data-icon="fa-solid fa-running" data-url="/100m">Atletismo</option>
                </select>

            </form>
        </div><br>

        <div class="containerp">
            <!-- Aquí se muestran los resultados de los partidos -->
            <div class="match">
                <!-- Código para mostrar los partidos -->
                {% for partidounca in partidouncas %}
                <div class="match-content">
                    <div class="column">
                        <div class="team team--home">
                            <div class="team-logo">
                                {% if partidounca.equipo_local.imagen %}
                                <img src="{{ partidounca.equipo_local.imagen.url }}" alt="" class="img-stylecup equipo-img">
                                {% endif %}
                            </div>
                            <h2 class="team-name">{{ partidounca.equipo_local.nombre }}</h2>
                            <div class="match-time-lapsed">
                                {% for eventosunca in partidounca.eventosunca_set.all %}
                                    {% if eventosunca.tipo == 'GOOOOL' %}
                                    <i class="fa fa-soccer-ball-o"></i> {{ eventosunca.jugadores }} {{ eventosunca.minuto }}'  <br>
                                    {% endif %}
                                    {% if eventosunca.tipo == 'TARJETA ROJA' %}
                                    <i class="fas fa-square redcard-icon"></i> {{ eventosunca.jugadores }} {{ eventosunca.minuto }}'  <br>
                                    {% endif %}
                                    {% if eventosunca.tipo == 'PUNTO' %}
                                    <i class="fa fa-hashtag"></i> {{ eventosunca.jugadores }} {{ eventosunca.minuto }}'  <br>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="column-match-details">
                        <div class="match-details">
                             <div class="match-referee">
                                <h7 class="h3-stylecup"><strong>{{ partidounca.get_deporte_display }}</strong></h7>
                            </div>
                        
                            <div class="match-date">
                                <strong>{{ partidounca.fecha }}</strong>
                            </div>
                            <div class="match-score">
                                {% for eventopartidounca in partidounca.eventopartidounca_set.all %}
                                {% if eventopartidounca.tipo == 'INICIO DEL PARTIDO' %}
                                <span class="match-score-number">{{ partidounca.goles_local }}</span>
                                <span class="match-score-divider">:</span>
                                <span class="match-score-number">{{ partidounca.goles_visitante }}</span>
                                    {% endif %}
                             {% endfor %}
                            </div>
                        
                            <div class="match-referee">
                                {{ partidounca.partido_numero }}: <strong>{{ partidounca.fase_partido }}</strong>
                            </div><br>
                            {% for eventopartidounca in partidounca.eventopartidounca_set.all %}
                                {% if eventopartidounca.tipo == 'INICIO DEL PARTIDO' %}
                            <button class="match-bet-place"><a style="color: white" href="{% url 'resumen' pk=partidounca.pk %}">RESUMEN</a></button>
                            {% endif %}
                                {% endfor %}
                                </div>
                    </div>
                    <div class="column">
                        <div class="team team--away">
                            <div class="team-logo">
                                {% if partidounca.equipo_visitante.imagen %}
                                <img src="{{ partidounca.equipo_visitante.imagen.url }}" alt="" class="img-stylecup equipo-img">
                                {% endif %}
                            </div>
                            <h2 class="team-name">{{ partidounca.equipo_visitante.nombre }}</h2>
                            <div class="match-time-lapsed">
                                {% for eventosunca in partidounca.eventosunca_set.all %}
                                    {% if eventosunca.tipo == 'GOOOL' %}
                                    <i class="fa fa-soccer-ball-o"></i> {{ eventosunca.jugadores }} {{ eventosunca.minuto }}'  <br>
                                    {% endif %}
                                    {% if eventosunca.tipo == 'TARJETA ROJA ' %}
                                    <i class="fas fa-square redcard-icon"></i> {{ eventosunca.jugadores }} {{ eventosunca.minuto }}'  <br>
                                    {% endif %}
                                    {% if eventosunca.tipo == 'PUNTO ' %}
                                    <i class="fa fa-hashtag"></i> {{ eventosunca.jugadores }} {{ eventosunca.minuto }}'  <br>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <br><br>
                {% endfor %}
            </div>
        </div>

    </section>
<!-- Blog section -->
	<section class="blog-section spad">
		<div class="container">
			<div class="section-title text-center">
                <h4><i class="fa fa-newspaper-o"></i> FEUNCA Noticias</h4>
				
			</div>
			<div class="row">
                {% for post in posts %}
				<div class="col-xl-6 col-md-6 col-sm-12">
					<div class="blog-item" id="blogItem">
						<div class="blog-thumb set-bg" data-setbg="{% static "image/" %}{{ post.foto }}"></div>
						<div class="blog-content">
                            <h4><a href="/noticias/{{ post.id }}" style="color:black">{{ post.title }}</a></h4>
							<div class="blog-meta">
								<span><i class="fa fa-calendar-o"></i> {{ post.published_date }} </span>
								<span><i class="fa fa-user"></i> {{ post.author }} </span>
							</div>
							<p>{{ post.text|truncatewords:"25" }}</p>
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>
	<!-- Blog section -->
    {% include "pie_pagina.html" %}

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#deporte').select2({
            templateResult: function(state) {
                if (!state.id) {
                    return state.text;
                }
                var iconClass = $(state.element).data('icon');
                var $state = $(
                    '<span><i class="' + iconClass + '"></i> ' + state.text + '</span>'
                );
                return $state;
            },
            templateSelection: function(state) {
                if (!state.id) {
                    return state.text;
                }
                var iconClass = $(state.element).data('icon');
                var $state = $(
                    '<span><i class="' + iconClass + '"></i> ' + state.text + '</span>'
                );
                return $state;
            }
        });
    
        $('#deporte').change(function() {
            var selectedOption = $(this).find('option:selected');
            var url = selectedOption.data('url');
    
            if (url) {
                // Si hay una URL asociada, redirigir
                window.location.href = url;
            } else {
                // De lo contrario, enviar el formulario
                $('#deporteForm').submit();
            }
        });
    });
    </script>
</body>
</html>